# Generated by Django 5.0.3 on 2024-04-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abbrev', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNumber', models.IntegerField(default=0)),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('Credits', models.TextField()),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='CourseCatalog.subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('CourseNumber', 'Subject'), name='number_subject_unique_contstraint'),
        ),
    ]
