# Generated by Django 5.0.3 on 2024-04-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CourseCatalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abbrev', models.CharField(max_length=1, unique=True)),
                ('Text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('CRN', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Section', models.TextField(null=True)),
                ('Cap', models.IntegerField(null=True)),
                ('Act', models.IntegerField(null=True)),
                ('Rem', models.IntegerField(null=True)),
                ('Professor', models.TextField(null=True)),
                ('Course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CourseCatalog.course')),
            ],
        ),
        migrations.CreateModel(
            name='OfferingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.TextField(null=True)),
                ('EndTime', models.TextField(null=True)),
                ('Day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Registrar.day')),
                ('Offering', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Registrar.offering')),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offering', models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='Registrar.offering')),
                ('Professor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='Registrar.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.TextField()),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Registrar.semester')),
            ],
        ),
        migrations.AddField(
            model_name='offering',
            name='Term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Registrar.term'),
        ),
        migrations.AddConstraint(
            model_name='offeringday',
            constraint=models.UniqueConstraint(fields=('Offering', 'Day'), name='offering_day_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='teaches',
            constraint=models.UniqueConstraint(fields=('Offering', 'Professor'), name='crn_professor_unique_contstraint'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('Year', 'Semester'), name='year_semester_unique_contstraint'),
        ),
    ]
